# Events Github Actions will respond to
#  https://docs.github.com/en/actions/reference/events-that-trigger-workflows#push
name: Deploy Project
# on: push
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # we need to get the code from the repository
      # https://github.com/marketplace/actions/checkout
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        # run: npm install     # para desarrollo/local
        run: npm ci # para entornos CI, recomendado en tu workflow
      - name: Run tests
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    # This job will run only if the previous job (test) was successful
    needs: test
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        # run: npm install     # para desarrollo/local
        run: npm ci # para entornos CI, recomendado en tu workflow
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: |
          echo "Deploying the project..."
          echo "deployyyyyyy"
